### ISSUE TITLE
change shibboleth to be only ucla sso

### ISSUE THREAD

**Issue by jt14den** [ucla-data-archive/ucla-dataverse#8]
figure out how to turn off federated.

**Comment by jt14den** [comment]
Don't think federated approach will work for our budget and needs

**Comment by jmjamison** [comment]
Non-federated uses an IdP file, ucla setup has you pulling  from <http://md.incommon.org/InCommon/InCommon-metadata-idp-only.xml> as well as a local downloaded local copy. This is where the gigantic list of institutions is. 

Since I don't have a non-ucla account I can't test logging in from one of the other institutions. 

This might be a question for the ucla/shibboleth people.

**Comment by jt14den** [comment]
Looked again and the metacdata providers till points to the federated service.

**Comment by jmjamison** [comment]
Yesterday tj4den edited the metadata provider file.  That seems to have fixed this problem.  When I logged into test.dataverse only choice was UCLA
